# Generated by Django 2.1 on 2018-08-13 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        ('tarefa', '0002_auto_20180812_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projeto.Projeto'),
            preserve_default=False,
        ),
    ]
